# Generated by Django 4.2.2 on 2025-10-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsphereApp', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(max_length=5000),
        ),
    ]
