# Generated by Django 4.2.2 on 2025-11-09 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsphereApp', '0004_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 9, 11, 23, 56, 134560, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
