# Generated by Django 5.2.7 on 2025-11-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventsphereApp", "0005_booking_booked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
